# Generated by Django 5.2 on 2025-04-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_thumbnail_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video_file',
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
