# Generated by Django 5.2 on 2025-04-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_date_added_movie_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
        migrations.AddField(
            model_name='movie',
            name='video_file',
            field=models.FileField(default='movies/test.mp4', upload_to='movies/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(default='thumbnails/thumbnail.jpg', upload_to='thumbnails/'),
        ),
    ]
